# Dockerfile
FROM public.ecr.aws/lambda/nodejs:18

# Copy app files
COPY appointment-service.js .  

# Set the Lambda function handler
CMD [ "appointment-service.handler" ]











































